export const State = {
    statboticsCache: {},
    wobotMatchData: [],
    activeProfileTeam: null,
    activeCompareFilters: [],
    compareSlotData: { left: null, right: null },
    radarChartInstance: null,
    pickLists: { 1: [], 2: [] },
    isOnline: true,
    currentUser: null,
    currentUserRole: "scouter",
    globalDataCache: [],
    activeEventKey: "Pending...",
    mainTableInstance: null,
    adminTableInstance: null,
    matchTableInstance: null,
    previousAssignmentCount: 0,
    syncProcesses: 0,
    returnViewOverride: null,
    returnScrollPos: 0,
    currentScheduleMatches: [],
    currentLiveMatch: "TBD",
};
